# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    env: 
      url: http://localhost
    permissions:
      contents: read
      packages: write

    steps:

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: chromeinstall
      uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    - uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.html
        reporter: java-junit
        fail-on-error: true
